#!/command/with-contenv bash
#shellcheck shell=bash

# shellcheck source=source-stubs/scripts/common
source /scripts/common

if [[ -z "$HOST_978" ]]; then
    stop_service
fi

exec s6wrap --quiet --timestamps --prepend=stats978 --args python3 -u /scripts/stats978.py
