#!/command/with-contenv bash
#shellcheck shell=bash

# shellcheck source=source-stubs/scripts/common
source /scripts/common

if [[ -n "$HOST_978" && -z "$INFLUXDB_SKIP_AIRCRAFT" ]]; then

  # less reconnect spam
  sleep 4

  SOCAT_CMD=("socat")

  if [ "$VERBOSE_LOGGING" = "true" ]; then
    SOCAT_CMD+=("-d" "-d")
  fi

  SOCAT_CMD+=("TCP:${HOST_978}:30979")
  SOCAT_CMD+=("TCP:localhost:33979")

  # shellcheck disable=SC2016
  exec s6wrap --quiet --timestamps --prepend="$(basename "$0")" --args "${SOCAT_CMD[@]}"

else
  stop_service
fi
